require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CollegePlayersController do

  # This should return the minimal set of attributes required to create a valid
  # CollegePlayer. As you add validations to CollegePlayer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CollegePlayersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all college_players as @college_players" do
      college_player = CollegePlayer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:college_players).should eq([college_player])
    end
  end

  describe "GET show" do
    it "assigns the requested college_player as @college_player" do
      college_player = CollegePlayer.create! valid_attributes
      get :show, {:id => college_player.to_param}, valid_session
      assigns(:college_player).should eq(college_player)
    end
  end

  describe "GET new" do
    it "assigns a new college_player as @college_player" do
      get :new, {}, valid_session
      assigns(:college_player).should be_a_new(CollegePlayer)
    end
  end

  describe "GET edit" do
    it "assigns the requested college_player as @college_player" do
      college_player = CollegePlayer.create! valid_attributes
      get :edit, {:id => college_player.to_param}, valid_session
      assigns(:college_player).should eq(college_player)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CollegePlayer" do
        expect {
          post :create, {:college_player => valid_attributes}, valid_session
        }.to change(CollegePlayer, :count).by(1)
      end

      it "assigns a newly created college_player as @college_player" do
        post :create, {:college_player => valid_attributes}, valid_session
        assigns(:college_player).should be_a(CollegePlayer)
        assigns(:college_player).should be_persisted
      end

      it "redirects to the created college_player" do
        post :create, {:college_player => valid_attributes}, valid_session
        response.should redirect_to(CollegePlayer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved college_player as @college_player" do
        # Trigger the behavior that occurs when invalid params are submitted
        CollegePlayer.any_instance.stub(:save).and_return(false)
        post :create, {:college_player => {}}, valid_session
        assigns(:college_player).should be_a_new(CollegePlayer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CollegePlayer.any_instance.stub(:save).and_return(false)
        post :create, {:college_player => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested college_player" do
        college_player = CollegePlayer.create! valid_attributes
        # Assuming there are no other college_players in the database, this
        # specifies that the CollegePlayer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CollegePlayer.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => college_player.to_param, :college_player => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested college_player as @college_player" do
        college_player = CollegePlayer.create! valid_attributes
        put :update, {:id => college_player.to_param, :college_player => valid_attributes}, valid_session
        assigns(:college_player).should eq(college_player)
      end

      it "redirects to the college_player" do
        college_player = CollegePlayer.create! valid_attributes
        put :update, {:id => college_player.to_param, :college_player => valid_attributes}, valid_session
        response.should redirect_to(college_player)
      end
    end

    describe "with invalid params" do
      it "assigns the college_player as @college_player" do
        college_player = CollegePlayer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CollegePlayer.any_instance.stub(:save).and_return(false)
        put :update, {:id => college_player.to_param, :college_player => {}}, valid_session
        assigns(:college_player).should eq(college_player)
      end

      it "re-renders the 'edit' template" do
        college_player = CollegePlayer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CollegePlayer.any_instance.stub(:save).and_return(false)
        put :update, {:id => college_player.to_param, :college_player => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested college_player" do
      college_player = CollegePlayer.create! valid_attributes
      expect {
        delete :destroy, {:id => college_player.to_param}, valid_session
      }.to change(CollegePlayer, :count).by(-1)
    end

    it "redirects to the college_players list" do
      college_player = CollegePlayer.create! valid_attributes
      delete :destroy, {:id => college_player.to_param}, valid_session
      response.should redirect_to(college_players_url)
    end
  end

end
